@URL_ACCOUNT=http://localhost:8081/account




### GET ALL
GET {{URL_ACCOUNT}}


### GET BY NUMBER
GET {{URL_ACCOUNT}}/12345

### CREATE
POST {{URL_ACCOUNT}}
Content-Type: application/json

{
    "name": "Ricardo Sobjak",
    "number": 12345,
    "balance": 1000,
    "specialLimit": 1000
}

### CREATE
POST {{URL_ACCOUNT}}
Content-Type: application/json

{
    "name": "Ana Campos",
    "number": 1234,
    "balance": 500,
    "specialLimit": 0
}

### CREATE INVALID
POST {{URL_ACCOUNT}}
Content-Type: application/json

{}

### UPDATE
PUT {{URL_ACCOUNT}}/20
Content-Type: application/json

{
    "name": "Ricardo Sobjak",
    "number": 11111,
    "balance": 1000,
    "specialLimit": 1000
}

### UPDATE NOT FOUND
PUT {{URL_ACCOUNT}}/20
Content-Type: application/json

{
    "name": "Ricardo Sobjak",
    "number": 11111,
    "balance": 1000,
    "specialLimit": 1000
}

### UPDATE INVALID
PUT {{URL_ACCOUNT}}/50
Content-Type: application/json

{}
