@URL_TRANSACTION}}=http://localhost:8081/transaction


### TRANSFER
POST {{URL_TRANSACTION}}/transfer
Content-Type: application/json

{
    "sourceAccountNumber": 12345,
    "receiverAccountNumber": 12346,
    "amount": 1000
}

### WITHDRAW
POST {{URL_TRANSACTION}}/withdraw
Content-Type: application/json

{
    "sourceAccountNumber": 12345,
    "amount": 1000
}



### DEPOSIT
POST {{URL_TRANSACTION}}/deposit
Content-Type: application/json

{
    "receiverAccountNumber": 12345,
    "amount": 2000
}
